backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: Settings
    name: settings
    files:
      - label: General
        name: general
        format: json
        file: 'assets/content/settings/general.json'
        fields:
          - { label: Title, name: title, widget: string, hint: 'The title of the website' }
          - { label: Favicon, name: icon, widget: image }
          - { label: 'Loading Color', name: loadingColor, widget: string, default: '#000000' }
      - label: Manifest
        name: manifst
        format: json
        file: 'assets/content/settings/styling.json'
        fields:
          - { label: Name, name: name, widget: string }
          - { label: 'Short name', name: shortName, widget: string }
          - { label: Description, name: description, widget: text }
          - { label: 'Theme color', name: themeColor, widget: string }
          - { label: 'Background color', name: backgroundColor, widget: string }
          - { label: Lang, name: lang, widget: string, default: en }
      - label: Social
        name: social
        format: json
        file: 'assets/content/settings/social.json'
        fields:
          - label: Icons
            name: icons
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Icon, name: icon, widget: image }
              - { label: url, name: url, widget: string }
      - label: Blog
        name: blog
        format: json
        file: 'assets/content/settings/blog.json'
        fields:
          - label: Categories
            name: categories
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Icon, name: icon, widget: image, default: '/static/img/icon.svg' }
              - { label: slug, name: slug, widget: string }

  - name: 'blog'
    label: 'Blog'
    format: json
    folder: assets/content/blog
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - label: 'Categories'
        name: 'category'
        widget: 'list'
        hint: 'Use a comma to provide separate categories'
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Featured Image', name: 'featured_image', widget: 'image', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'about_pages'
    label: 'About Page'
    format: 'json'
    files:
      - label: 'Profile Page'
        name: "about_profile"
        file: "assets/content/pages/about/profile.json"
        fields:
          - { label: Portrait, name: portrait, widget: image }
          - { label: Content, name: content, widget: markdown }
          - { label: Icon, name: icon, required: false }
      - label: 'Skills Page'
        name: "about_skills"
        file: "assets/content/pages/about/skills.json"
        fields:
          - label: Categories
            name: categories
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - label: Subcategories
                name: subcategories
                widget: list
                fields:
                  - { label: Name, name: name, widget: string }
                  - { label: Icon, name: icon, widget: image }
                  - { label: Overview, name: overview, widget: markdown }
                  - { label: Examples, name: examples, widget: markdown }
          - { label: Icon, name: icon, required: false }
      - label: 'Education Page'
        name: "about_education"
        file: "assets/content/pages/about/education.json"
        fields:
          - label: Institutions
            name: institutions
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Logo, name: logo, widget: image }
              - { label: Banner, name: banner, widget: image, required: false }
              - { label: Content, name: content, widget: markdown }
          - { label: Icon, name: icon, required: false }

  - name: 'project_pages'
    label: 'Project Page'
    format: 'json'
    slug: '{{slug}}'
    create: true
    folder: 'assets/content/pages/projects/'
    fields:
        - { label: Title, name: title, widget: string }
        - label: Images
          name: images
          widget: list
          field: { label: Image, name: image, widget: image }
        - { label: Content, name: content, widget: markdown }
        - label: Meta
          name: meta
          required: false
          widget: list
          fields:
            - { label: Key, name: key, widget: string }
            - { label: Value, name: value, widget: string }