backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: Settings
    name: settings
    files:
      - label: General
        name: general
        format: json
        file: 'assets/content/settings/general.json'
        fields:
          - { label: Title, name: title, widget: string, hint: 'The title of the website' }
          - { label: Favicon, name: icon, widget: image }
          - { label: 'Loading Color', name: loadingColor, widget: string, default: '#000000' }
      - label: Manifest
        name: manifst
        format: json
        file: 'assets/content/settings/styling.json'
        fields:
          - { label: Name, name: name, widget: string }
          - { label: 'Short name', name: shortName, widget: string }
          - { label: Description, name: description, widget: text }
          - { label: 'Theme color', name: themeColor, widget: string }
          - { label: 'Background color', name: backgroundColor, widget: string }
          - { label: Lang, name: lang, widget: string, default: en }
      - label: Social
        name: social
        format: json
        file: 'assets/content/settings/social.json'
        fields:
          - label: Icons
            name: icons
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Icon, name: icon, widget: image }
              - { label: url, name: url, widget: string }

  - name: 'about_pages'
    label: 'About Page'
    format: 'json'
    files:
      - label: 'Profile Page'
        name: "about_profile"
        file: "assets/content/pages/about/profile.json"
        fields:
          - { label: Portrait, name: portrait, widget: image }
          - { label: Content, name: content, widget: markdown }
      - label: 'Skills Page'
        name: "about_skills"
        file: "assets/content/pages/about/skills.json"
        fields:
          - label: Skills
            name: skills
            widget: list
            fields:
              - { label: Label, name: label, widget: string }
              - { label: Name, name: name, widget: string }
              - { label: Type, name: type, widget: string }
              - { label: Icon, name: icon, widget: image }
      - label: 'Education Page'
        name: "about_education"
        file: "assets/content/pages/about/education.json"
        fields:
          - label: Institutions
            name: institutions
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Logo, name: logo, widget: image }
              - { label: Banner, name: banner, widget: image, required: false }
              - { label: Content, name: content, widget: markdown }

  - name: 'project_pages'
    label: 'Project Page'
    format: 'json'
    slug: '{{slug}}'
    create: true
    folder: 'assets/content/pages/projects/'
    fields:
        - { label: Title, name: title, widget: string }
        - label: Carousel Items
          name: carouselItems
          widget: list
          fields: 
            - { label: Description, name: alt, widget: string }
            - label: Images
              name: images
              widget: list
              fields: 
                - { label: Source, name: source, widget: image, allow_multiple: true, media_library: { config: { multiple: true } } }
        - label: Images
          name: images
          widget: list
          field: { label: Image, name: image, widget: image }
        - { label: About, name: about, widget: markdown }
        - label: Tech Stack
          name: stack
          widget: relation
          collection: 'about_pages'
          file: 'about_skills'
          search_fields: ["skills.*.name"]
          value_field: "skills.*.name"
          display_fields: ["skills.*.name"]
          multiple: true
        - label: Resources
          name: resources
          widget: list
          required: false
          fields:
            - { label: Path, name: path, widget: string }
            - { label: Label, name: label, widget: string }
        - { label: 'Web Address', name: url, widget: string, required: false }
        - label: Meta
          name: meta
          required: false
          widget: list
          fields:
            - { label: Key, name: key, widget: string }
            - { label: Value, name: value, widget: string }